version: '3.8'

services:
  recipe-app:
    container_name: recipe-app
    build:
      context: .
      target: $TARGET
      args:
        NODE_ENV: $NODE_ENV
    volumes:
      - ./src:/app/src
    ports:
      - $PORT:$PORT
    

networks:
  default:
    external:
      name: kukku-bukku-network